# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sauerstoff
tagline:             'Scale Modelling and Sundry Geekery'
description:         'A self indulgent expos√© of modelling, gaming, code and whatever else I fancy.'
url:                 http://www.sauerstoff.ca
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Derek Sauer
  url:               http://www.sauerstoff.ca
  email:             dereksauer.ca@gmail.com

# Custom vars
version:             1.0.0
